/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pfinal;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;

/**
 * Clase LienzoImagen, añade funcionalidades de imagen a la clase Lienzo. 
 * @author Mario
 */
public class LienzoImagen extends Lienzo {

    /**
     * Creates new form LienzoImagen
     */
    private BufferedImage image;
    private boolean imagen_cambiada = false;
    
    /**
     * Constructor de la clase.
     * @param altura Define la altura del lienzo.
     * @param anchura Define la anchura del lienzo.
     */
    public LienzoImagen(int altura, int anchura) {
        initComponents();
        imagenBlanco(altura, anchura);
    }
    
    /**
     * Crea una nueva imagen en blanco en caso de no haber sido cambiada la imagen
     * @param altura Define la altura del lienzo.
     * @param anchura Define la anchura del lienzo.
     */
    public void imagenBlanco(int altura, int anchura){
        if (!imagen_cambiada){
            BufferedImage nueva = new BufferedImage(anchura, altura, BufferedImage.TYPE_3BYTE_BGR);
            Graphics2D g2 = nueva.createGraphics();

            g2.setColor(Color.white);
            g2.fillRect(0, 0, this.getWidth(), this.getHeight());
            paintFormas(nueva.createGraphics());

            image = nueva;
        }
    }
    
    /**
     * Establece una imagen como propia del lienzo y cambia el parametro imagen cambiada
     * @param img Imagen a establecer como propia del lienzo.
     */
    public void setImage(BufferedImage img){
        setPreferredSize(new Dimension(img.getWidth(),img.getHeight()));
        image = img;
        imagen_cambiada = true;
    }
    /**
     * 
     * @return Devuelve la imagen propia del lienzo.
     */
    public BufferedImage getImage(){
        return image;
    }
    /**
     * Función que guarda el lienzo con todas sus formas y su imagen (si tiene) como una imagen.
     * @return Devuelve la imagen con toas las nuevas transformaciones y formas ya guardadas.
     */
    public BufferedImage guardar(){
        if(image != null){
            BufferedImage nueva = new BufferedImage(image.getWidth(), image.getHeight(), image.getType());
            nueva.setData(image.getData());
            paintFormas(nueva.createGraphics());
            return nueva;
        }else{
            return null;
        }
       
    }

    /**
     * Funcion sobrecargada que pinta en el lienzo la imagen (si la hay) y las formas.
     * @param g 
     */
    @Override
    public void paintComponent(Graphics g){
          super.paintComponent(g);
          if(image!=null) g.drawImage(image,0,0,this);
          super.paintFormas(g);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Función usada cuando cambia el tamaño del lienzo.
     * @param evt 
     */
    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        imagenBlanco(this.getHeight(), this.getWidth());
    }//GEN-LAST:event_formComponentResized

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
