/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pfinal;

import java.awt.Component;
import java.io.File;
import javax.media.Manager;
import javax.media.MediaLocator;
import javax.media.Player;

/**
 * Clase de reproducción de video.
 * @author Mario
 */
public class VentanaReproduccionJMF extends javax.swing.JInternalFrame {

    private Player p;
    private MediaLocator ml;
    
    /**
     * Crea una nueva ventana de reproduccion de video.
     * @param f Archivo de video a reproducir.
     */
    public VentanaReproduccionJMF(File f) {
        try{
            initComponents();
            ml = new MediaLocator(f.toURL());
            p = Manager.createRealizedPlayer(ml);
            Component areaVisual = p.getVisualComponent();
            if(areaVisual!=null){
                this.add(areaVisual);
            }
            Component pControl = p.getControlPanelComponent();
            if(pControl!=null) this.add(pControl);
            pack();
        }catch(Exception e){
            System.err.println("Error al abrir el video");
        }
    }
    
    /**
     * 
     * @return Devuelve el player que está en uso.
     */
    public Player getPlayer(){
        return p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
