/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pfinal;

import java.io.File;
import javax.sound.sampled.LineEvent;
import javax.sound.sampled.LineEvent.Type;
import javax.sound.sampled.LineListener;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import sm.sound.SMClipPlayer;
import sm.sound.SMPlayer;

/**
 * Clase de la ventada de reproducción de audio.
 * @author Mario
 */
public class VentanaReproduccion extends javax.swing.JInternalFrame {

    
    
    SMPlayer player;
    /**
     * Crea una nueva ventana de reproducción.
     * @param f Archivo de audio a reproducir.
     */
    public VentanaReproduccion(File f) {
           initComponents();
           player = new SMClipPlayer(f);
           
           botonPlay.setSelectedIcon(new ImageIcon(this.getClass().getResource("/pfinal/iconos/PlayPressed_48x48.png")));
           botonPlay.setIcon(new ImageIcon(this.getClass().getResource("/pfinal/iconos/PlayDisabled_48x48.png")));
           botonStop.setSelectedIcon(new ImageIcon(this.getClass().getResource("/pfinal/iconos/StopNormalRed_48x48.png")));
           botonStop.setIcon(new ImageIcon(this.getClass().getResource("/pfinal/iconos/StopDisabled_48x48.png")));
           
           LineListener lineListener=new LineListener(){
               public void update(LineEvent event) {
                 if(event.getType()==Type.START) {
                    botonStop.setSelected(false);
                 }
                 if(event.getType()==Type.STOP) {
                    botonPlay.setSelected(false);
                    
                    botonStop.setSelected(true);
                    
                 }
            } 
            };
               
            ((SMClipPlayer)player).setLineListener(lineListener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        botonPlay = new javax.swing.JToggleButton();
        botonStop = new javax.swing.JToggleButton();

        setClosable(true);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        buttonGroup1.add(botonPlay);
        botonPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pfinal/iconos/PlayDisabled_48x48.png"))); // NOI18N
        botonPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPlayActionPerformed(evt);
            }
        });
        getContentPane().add(botonPlay);

        buttonGroup1.add(botonStop);
        botonStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pfinal/iconos/StopNormalRed_48x48.png"))); // NOI18N
        botonStop.setSelected(true);
        botonStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonStopActionPerformed(evt);
            }
        });
        getContentPane().add(botonStop);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Inicia la reproducción del audio.
     * @param evt 
     */
    private void botonPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPlayActionPerformed
        if(player!=null)  player.play();
    }//GEN-LAST:event_botonPlayActionPerformed

    /**
     * Para la reproducción del audio.
     * @param evt 
     */
    private void botonStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonStopActionPerformed
        if(player!=null) player.stop();
    }//GEN-LAST:event_botonStopActionPerformed

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton botonPlay;
    private javax.swing.JToggleButton botonStop;
    private javax.swing.ButtonGroup buttonGroup1;
    // End of variables declaration//GEN-END:variables
}
