/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pfinal;

/**
 * Clase de la ventana de imagen.
 * @author Mario
 */
public class VentanaImagen extends javax.swing.JInternalFrame {

    /**
     * Constructor de la clase.
     * @param altura Define la altura de la ventana y el lienzo.
     * @param anchura Define la anchura de la ventana y el lienzo.
     */
    public VentanaImagen(int altura, int anchura) {
        setSize(anchura, altura);
        initComponents(altura, anchura);
        lienzoImagen1.setSize(anchura, altura);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    /**
     * 
     * @return Devuelve el LienzoImagen propio de la ventana.
     */
    public LienzoImagen getLienzo(){
        return lienzoImagen1;
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents(int altura, int anchura) {

        jScrollPane1 = new javax.swing.JScrollPane();
        lienzoImagen1 = new pfinal.LienzoImagen(altura, anchura);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Nuevo");
        setSize(new java.awt.Dimension(150, 150));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        org.jdesktop.layout.GroupLayout lienzoImagen1Layout = new org.jdesktop.layout.GroupLayout(lienzoImagen1);
        lienzoImagen1.setLayout(lienzoImagen1Layout);
        lienzoImagen1Layout.setHorizontalGroup(
            lienzoImagen1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, anchura, Short.MAX_VALUE)
        );
        lienzoImagen1Layout.setVerticalGroup(
            lienzoImagen1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, altura, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(lienzoImagen1);

        getContentPane().add(jScrollPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized

    }//GEN-LAST:event_formComponentResized

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private pfinal.LienzoImagen lienzoImagen1;
    // End of variables declaration//GEN-END:variables
}
