/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pfinal;

import java.awt.Component;
import java.util.Vector;
import javax.media.CaptureDeviceInfo;
import javax.media.Manager;
import javax.media.MediaLocator;
import javax.media.Player;
import javax.media.cdm.CaptureDeviceManager;
import javax.media.format.YUVFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 * Ventana de la WebCam.
 * @author Mario
 */
public class VentanaCamara extends javax.swing.JInternalFrame {

    private MediaLocator ml=null;
    private Player p = null;
    /**
     * Crea una nueva instancia de VentanaCamara y usa como dispositivo de captura el primero de la lista.
     * NO FUNCIONA.
     */
    public VentanaCamara() {
        try{
            initComponents();
            CaptureDeviceInfo device_info;
            Vector<CaptureDeviceInfo> device_list = CaptureDeviceManager.getDeviceList(new YUVFormat());
            device_info = device_list.elementAt(0);
            //System.out.println(device_info.toString());
            ml = device_info.getLocator();
            p = Manager.createRealizedPlayer(ml);
            Component areaVisual = p.getVisualComponent();
            if(areaVisual!=null){
                this.add(areaVisual);
            }
            Component pControl = p.getControlPanelComponent();
            if(pControl!=null) this.add(pControl);
            pack();
        }catch(Exception e){
            JOptionPane.showMessageDialog(new JFrame(), "No se puede abrir el capturador de video.", "Error al abrir la webcam", JOptionPane.ERROR_MESSAGE);
            
        }
    }
    
    /**
     * 
     * @return Devuelve el player asociado la ventana.
     */
    public Player getPlayer(){
        return p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("webcam");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
